apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  selector:
    matchLabels:
      app: identity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - image: itdaos/dvc-identity:latest
        name: identity
