apiVersion: apps/v1
kind: Deployment
metadata:
  name: art
spec:
  selector:
    matchLabels:
      app: art
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: art
    spec:
      containers:
      - image: itdaos/dvc-art:latest
        name: art
