apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: itdaos/dvc-gateway:latest
        ports:
        - name: http
          containerPort: 4444
          
